<a href="https://colab.research.google.com/github/sipark1958/Data-Analysis-with-Open-Source/blob/main/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_2%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# 오픈소스 기반 데이터 분석 2강 - 데이터 분석을 위한 파이썬 1


# 새 섹션

In [ ]:
 import tensorflow as tf
 import numpy as np
 import pandas as pd
 import matplotlib.pyplot as plt

In [ ]:
a = tf.constant(10.)
b = tf.constant([1,2,3,4])
c = tf.constant([[[1,2],[3,4],[5,6]], [[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]],[[19,20],[21,22],[23,24]]], dtype = tf.float32)
print('a: type =', a.dtype, '\n',a)
print('b: shape =', b.shape, '\n',b)
print('c: device =', c.device)

a: type = <dtype: 'float32'> 
 tf.Tensor(10.0, shape=(), dtype=float32)
b: shape = (4,) 
 tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
c: device = /job:localhost/replica:0/task:0/device:CPU:0


In [ ]:
x = tf.Variable(10.)
y = tf.Variable([[1.,2.,3.], [4., 5., 6.]])
z = np.array([[1.,3.],[2.,4.], [3.,5.]], dtype = np.float32)
print('x: dtype =', x.dtype, '\n',x)
print('y: shape =', y.shape, '\n',y)
print('z: device =', z.device)

x: dtype = <dtype: 'float32'> 
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.0>
y: shape = (2, 3) 
 <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>
z: device = cpu


In [ ]:
x.assign_add(20.)
print('x = ', x.numpy())

x =  30.0


In [ ]:
print('a*b =', (a*tf.cast(b, tf.float32)).numpy())
print('tf.math.exp(y) =', tf.exp(y))
print('tf.math.reduce_sum(c, axis=2) =', tf.reduce_sum(c, axis=2))

a*b = [10. 20. 30. 40.]
tf.math.exp(y) = tf.Tensor(
[[  2.7182817   7.389056   20.085537 ]
 [ 54.59815   148.41316   403.4288   ]], shape=(2, 3), dtype=float32)
tf.math.reduce_sum(c, axis=2) = tf.Tensor(
[[ 3.  7. 11.]
 [15. 19. 23.]
 [27. 31. 35.]
 [39. 43. 47.]], shape=(4, 3), dtype=float32)


In [ ]:
print('tf.linalg.matmul(y,z) =')
print(tf.matmul(y,z))
print('np.matmul(y, z) =')
print(np.matmul(y,z))

tf.linalg.matmul(y,z) =
tf.Tensor(
[[14. 26.]
 [32. 62.]], shape=(2, 2), dtype=float32)
np.matmul(y, z) =
[[14. 26.]
 [32. 62.]]


In [ ]:
x1 = tf.Variable(3.)
x2 = tf.Variable(1., trainable=False)
with tf.GradientTape() as t:
    t.watch(x2)
    y = (x1 + 2*x2)**2
dy_dx = t.gradient(y, [x1, x2])
print(f'dy_dx1 = {dy_dx[0]}')
print(f'dy_dx2 = {dy_dx[1]}')

dy_dx1 = 10.0
dy_dx2 = 20.0


## 2-1 리스트 슬라이싱

In [3]:
numbers = [10, 20, 30, 40, 50, 60, 70]
# 첫 4개의 원소 출력
first_four =  numbers[0:4]
print(first_four)
# 뒤 3개의 원소를 출력
last_three = numbers[-3:]
print(last_three)

[10, 20, 30, 40]
[50, 60, 70]


In [4]:
numbers = [10, 20, 30, 40, 50, 60, 70]

# 홀수번째 항목 출력
every_other_list = numbers[::2]
print(every_other_list)

# 역순 출력
reverse_list = numbers[::-1]
print(reverse_list)

[10, 30, 50, 70]
[70, 60, 50, 40, 30, 20, 10]


# 새 섹션

# 새 섹션

In [ ]:
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

# 첫 두 행 출력


print(first_two_rows)

# 첫 두 열 출력


print(first_two_columns)

## 2-2 리스트 컴프리헨션

In [ ]:
numbers = [ ]

# 1 ~ 5 포함 리스트 생성
for i in range(5):
    numbers.append(i)

print(numbers)

In [ ]:
numbers = [1, 2, 3, 4, 5]
squares = [ ]

# numbers의 모든 항목의 값을 제곱한 리스트
for num in numbers:
  squares.append(num ** 2)

print(squares)

In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_numbers = [ ]

# 짝수만 추출한 리스트
for num in numbers:
    if num % 2 == 0:
        even_numbers.append(num)

print(even_numbers)

In [ ]:
list1 = ['사과', '복숭아', '바나나']
list2 = ['주스', '잼', '통조림']
pairs = [ ]

# 두 리스트에 포함되 모든 원소를 조합한 투플의 리스트 생성
for fruit in list1:
    for product in list2:
        pairs.append((fruit, product))

print(pairs)

In [ ]:
squares = { }

# 딕셔너리 생성
for i in range(5):
    squares[i] = i ** 2

print(squares)

In [ ]:
city_population = {
    '서울': 957, '부산': 339, '인천': 294, '대구': 242, '광주': 145, '대전': 147,
    '울산': 114, '세종': 36, '수원': 115, '창원': 103, '고양': 105, '용인': 108, '성남': 94
}

# 인구 200만명 이상의 도시 리스트

print(large_cities)

# 인구 300만 이상 및 이름에 '산'이 포함된 도시 리스트

print(large_short_name_cities)

## 2-3 문자열 형식화

In [ ]:
name = '홍길동'
age = 30
salary = 3500000
tax_rate = 0.1

# C 스타일 문자열 포매팅
# 이름, 나이, 월급 출력

# 직원이름, 나이, 세후 월급 출력


# 직원이름, 나이, 월급, 세금, 실수령액 추력


print(basic_format)
print(index_format)
print(keyword_format)

In [ ]:
name = '홍길동'
age = 30
salary = 3500000
tax_rate = 0.1

# str.format 문자열 포매팅
# 이름, 나이, 월급 출력

# 직원이름, 나이, 세후 월급 출력

# 직원이름, 나이, 월급, 세금, 실수령액 추력


print(basic_format)
print(index_format)
print(keyword_format)

In [ ]:
name = '홍길동'
age = 30
salary = 3500000
tax_rate = 0.1

# f-문자열 포매팅
# 이름, 나이, 월급 출력

# 직원이름, 나이, 세후 월급 출력

# 직원이름, 나이, 월급, 세금, 실수령액 추력


print(basic_format)
print(index_format)
print(keyword_format)

## 2-4 컨텍스트 관리

In [ ]:
# 파일 오픈 & 클로즈
file = open('output.txt', 'w')
file.write('Hello, world!\n')


In [ ]:
# 복수개의 파일(읽기 & 쓰기) 관리



In [ ]:
import urllib.request

# URL 연결 관리
('https://raw.githubusercontent.com/jaehwachung/Data-Analysis-with-Open-Source/refs/heads/main/Chapter%203/students.csv')
    data = response.read( ).decode('utf-8')

print(data)